version: "3.8"

services:
  kiosk-llm:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: kiosk-llm-prod
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - ENV=production
      - LOG_LEVEL=INFO
      - SQLITE_DB_PATH=/app/data/kiosk_llm.db
    devices:
      # Camera device
      - /dev/video0:/dev/video0
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - sqlite-db

  # Database service for production
  sqlite-db:
    image: alpine:latest
    container_name: kiosk-sqlite-prod
    volumes:
      - ./data:/data
    command:
      [
        "sh",
        "-c",
        "apk add --no-cache sqlite && sqlite3 /data/kiosk_llm.db 'SELECT 1;' && while true; do sleep 30; done",
      ]
    environment:
      - SQLITE_DB_PATH=/data/kiosk_llm.db
    restart: always

networks:
  default:
    name: kiosk-network
